# Rtistry from Albert Rapp

# Using ggforce to draw interesting patterns
# https://albert-rapp.de/posts/ggplot2-tips/05_ggforce_examples/05_ggforce_examples

# Hex Flag Colors
# https://fgeerolf.com/data/flags/index.html

library(tidyverse)
#install.packages("ggforce")
library(ggforce)
library (patchwork)

# Section 1

# A) General equation for generating the voronoi tiles

set.seed(23479)
N <- 1000
voronoi_1 <- tibble(x = runif(N), y = runif(N)) %>% 
  ggplot(aes(x, y)) +
  geom_voronoi_tile(aes(fill = y))

# B) Sample voronoi image generated by Albert Rapp

voronoi_1 +
  scale_fill_viridis_c(option = 'A') +
  theme_void() + 
  theme(legend.position = 'none')
  
# The option can be set between 'A' and 'H' and 
# Or it can be either "magma", "inferno", "plasma", "viridis", 
# "cividis", "rocket", "mako", or "turbo."

# The viridis scales provide colour maps that are 
# perceptually uniform in both colour and black-and-white. 
# They are also designed to be perceived by viewers with 
# common forms of colour blindness.

# https://ggplot2.tidyverse.org/reference/scale_viridis.html#ref-examples

# C) Set of Flags (Equation 1)
  
# Flag of the East African Community (EAC)

eac <- voronoi_1 +
  scale_fill_gradientn(colours = c("#418FDE", "#FFFFFF", "#D90000", "#006600","#FBD016", "#006600", "#000000",  "#FFFFFF",  "#418FDE")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "East African Community")
eac

# Flag of Kenya

ken_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#006600", "#FFFFFF", "#BB0000", "#FFFFFF", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Kenya")

# Flag of Tanzania

tan_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#00A3DD", "#FBD016", "#000000", "#FBD016","#1EB53A")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Tanzania")

# Flag of Uganda

uga_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#D90000", "#FCDC04", "#000000", "#FFFFFF", "#D90000", "#FCDC04", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Uganda")

# Flag of Rwanda

rwa_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#20603D", "#FAD201", "#00A1DE", "#00A1DE")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Rwanda")

# Flag of Burundi

bur_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#CE1126", "#1EB53A", "#FFFFFF", "#1EB53A", "#CE1126")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Burundi")

# Flag of DRC

drc_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#007FFF", "#F7D518", "#CE1021", "#F7D518", "#007FFF")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Democratic Republic of Congo")

# Flag of South Sudan

ssud_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#078930", "#FFFFFF", "#DA121A", "#0F47AF", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "South Sudan")

# Flag of Somalia

som_1 <- voronoi_1 +
  scale_fill_gradientn(colours = c("#418FDE", "#FFFFFF", "#418FDE")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Somalia")

(ken_1 + tan_1 + uga_1 + rwa_1) /  (bur_1 + drc_1 + ssud_1 + som_1)

# Section 2

# A) General equation for generating the voronoi tiles

set.seed(23479)
N <- 1000
voronoi_2 <- tibble(x = runif(N, -1, 1), y = sqrt(abs(x) + runif(N))) %>%  
  ggplot(aes(x, y)) +
  geom_voronoi_tile(aes(fill = y))

# B) Sample voronoi image generated by Albert Rapp

voronoi_2 +
  scale_fill_viridis_c(option = 'A') +
  theme_void() + 
  theme(legend.position = 'none')

# Flag of Kenya

ken_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#006600", "#FFFFFF", "#BB0000", "#FFFFFF", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Kenya")

# Flag of Tanzania

tan_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#00A3DD", "#FBD016", "#000000", "#FBD016","#1EB53A")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Tanzania")

# Flag of Uganda

uga_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#D90000", "#FCDC04", "#000000", "#FFFFFF", "#D90000", "#FCDC04", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Uganda")

# Flag of Rwanda

rwa_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#20603D", "#FAD201", "#00A1DE", "#00A1DE")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Rwanda")

# Flag of Burundi

bur_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#CE1126", "#1EB53A", "#FFFFFF", "#1EB53A", "#CE1126")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Burundi")

# Flag of DRC

drc_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#007FFF", "#F7D518", "#CE1021", "#F7D518", "#007FFF")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Democratic Republic of the Congo")

# Flag of South Sudan

ssud_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#078930", "#FFFFFF", "#DA121A", "#0F47AF", "#000000")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "South Sudan")

# Flag of Somalia

som_2 <- voronoi_2 +
  scale_fill_gradientn(colours = c("#418FDE", "#FFFFFF", "#418FDE")) +
  theme_void() + 
  theme(legend.position = 'none',
        plot.title = element_text(size = 12, hjust = 0.5)) +
  labs(title = "Somalia")

(ken_2 + tan_2 + uga_2 + rwa_2) /  (bur_2 + drc_2 + ssud_2 + som_2)

